AWSTemplateFormatVersion: "2010-09-09"
Description: "Firebox Cloud Lambda KMS Key"
Parameters: 
  ParamAdminUserArn: 
    Type: String
    Description: "Arn for Admin User"
  ParamStackName: 
    Type: String
    Description: Name used in resource tags and names
Resources:
  FireboxKmsKey:
    Type: "AWS::KMS::Key"
    Properties: 
      Description: "KMS Key for Firebox Configuration"
      Enabled: True
      EnableKeyRotation: True
      KeyPolicy: 
        Version: "2012-10-17"
        Id: "key-default-1"
        Statement: 
          - 
            Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal: 
              AWS: !Ref ParamAdminUserArn
            Action: 
              - "kms:*"
            Resource: "*"
          - 
            Sid: "Allow use of the key"
            Effect: "Allow"
            Principal: 
              AWS: !ImportValue FireboxLambdaCLIRoleArn
            Action: 
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
Outputs:
  FireboxKmsKeyArn:
    Description: Firbox KMS Key
    Value: !GetAtt FireboxKmsKey.Arn
    Export:
      Name: "FireboxKmsKeyArn"
