AWSTemplateFormatVersion: "2010-09-09"
Description: "Firebox Configuration Lambda"
Resources:
  FireboxConfigurationLambda:
    Type: "AWS::Lambda::Function"
    Properties: 
      Code:
        S3Bucket: !ImportValue FireboxPrivateBucket
        S3Key: fireboxconfig.zip
      Description: Firebox Lambda to Execute CLI Commands
      Environment:
        Variables:
          Bucket: !ImportValue FireboxPrivateBucket
          FireboxIp: !ImportValue FireboxPrimaryManagementIpAddress
      FunctionName: ConfigureFirebox
      Handler: fireboxconfig.configure_firebox
      KmsKeyArn: !ImportValue FireboxKmsKeyArn
      MemorySize: 128
      Role: !ImportValue FireboxLambdaCLIRoleArn
      Runtime: python2.7
      Timeout: 60
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue FireboxLambdaSecurityGroup
        SubnetIds:
          - !ImportValue FireboxManagementSubnet