AWSTemplateFormatVersion: "2010-09-09"
Description: "Firebox Configuration Lambda"
Parameters: 
  ParamVersion: 
    Type: String
    Default: "version1"
    Description: "Unique Version"
Resources:
  FireboxConfigurationLambda:
    Type: "AWS::Lambda::Function"
    Properties: 
      Code:
        S3Bucket: !ImportValue FireboxPrivateBucket
        S3Key: fireboxconfig.zip
      Description: Firebox Lambda to Execute CLI Commands
      Environment:
        Variables:
          Bucket: !ImportValue FireboxPrivateBucket
          FireboxIp: !ImportValue FireboxPrimaryPrivateIpAddress
      FunctionName: ConfigureFirebox
      Handler: fireboxconfig.configure_firebox
      KmsKeyArn: !ImportValue FireboxKmsKeyArn
      MemorySize: 128
      Role: !ImportValue FireboxLambdaCLIRoleArn
      Runtime: python3.6
      Timeout: 5
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue FireboxManagementSecurityGroup
        SubnetIds:
          - !ImportValue FireboxCLISubnet
  FireboxLambdaVersion:
    Type: "AWS::Lambda::Version"
    Properties:
      Description: !Ref ParamVersion   
      FunctionName : !Ref FireboxConfigurationLambda