AWSTemplateFormatVersion: "2010-09-09"
Description: "Firebox Configuration Lambda"
Parameters: 
  ParamStackName: 
    Type: String
    Description: "Name used in resource tags and names"
  ParamManagementCidr: 
    Type: String
    Description: "Cidr Block for Management"
  ParamAdminCidr: 
    Type: String
    Description: "Cidr Block for Admin Users"
  
Resources:
  FireboxConfigurationLambda:
    Type: "AWS::Lambda::Function"
    Properties: 
      Code:
        S3Bucket: !ImportValue FireboxPrivateBucket
        S3Key: fireboxconfig.zip
      Description: Firebox Lambda to Execute CLI Commands
      Environment:
        Variables:
          Bucket: !ImportValue FireboxPrivateBucket
          FireboxIp: !ImportValue FireboxPrimaryManagementIpAddress
          ManagementCidr: !Ref ParamManagementCidr
          AdminCidr: !Ref ParamAdminCidr
      
      FunctionName: ConfigureFirebox
      Handler: fireboxconfig.configure_firebox
      KmsKeyArn: !ImportValue FireboxKmsKeyArn
      MemorySize: 128
      Role: !ImportValue FireboxLambdaCLIRoleArn
      Runtime: python2.7
      Timeout: 180
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue FireboxManagementSecurityGroup
        SubnetIds:
          - !ImportValue FireboxManagementSubnet
      Tags:
        - Key: Name
          Value: FireboxLambda
        - Key: Stack
          Value: !Ref ParamStackName