AWSTemplateFormatVersion: "2010-09-09"
Description: "Firebox FlowLogs Role"
Parameters: 
  ParamStackName: 
    Type: String
    Description: "Name used in resource tags and names"
Resources:
  FireboxFlowLogRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: "FireboxFlowLogRole"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "vpc-flow-logs.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
  FireboxRolePolicy: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "FireboxFlowLogPolicy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: 
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
              - "logs:DescribeLogGroups"
              - "logs:DescribeLogStreams"
            Resource: "*"
      Roles: 
        - 
          Ref: "FireboxFlowLogRole"
Outputs:
  FireboxFlowLogsRoleArn:
    Description: ARN of FlowLogsRoleArn
    Value: !GetAtt FireboxFlowLogRole.Arn
    Export:
      Name: "FireboxFlowLogsRoleArn"