AWSTemplateFormatVersion: "2010-09-09"
Description: "Firebox Cloud VPC"

Parameters: 

  ParamStackName: 
    Type: String
    Default: "firebox-trial"
    Description: "Name used in resource tags and names"
  ParamVPCCidr: 
    Type: String
    Default: "10.0.0.0/16"
    Description: "CIDR block for VPC"

Resources:

  FireboxVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 
        Ref: ParamVPCCidr
      EnableDnsSupport: true
      Tags:
      - Key: Name
        Value: FireboxCloudVPC
      - Key: Stack
        Value: 
          Ref: ParamStackName
Outputs:
  FireboxVPC:
    Value: !Ref FireboxVPC
    Export:
      Name: FireboxVPC
  FireboxVpcCidr:
    Value: !GetAtt FireboxVPC.CidrBlock
    Export:
      Name: FireboxVPCCidr