AWSTemplateFormatVersion: "2010-09-09"
Description: "Firebox Cloud"
Parameters: 
  ParamFireboxAMI:
    Type: String
    Default: ami-ac1798cc
    AllowedValues:
      - ami-ac1798cc
  ParamInstanceType: 
    Type: String
    Default: c4.large
    AllowedValues: 
      - t2.micro
      - t2.small
      - c4.large
    Description: Choose an allowed instance type.
  ParamStackName: 
    Type: String
    Default: "firebox-trial"
    Description: "Name used in resource tags and names"
Resources:
  FireboxPublicNetworkInterface:
    Type: "AWS::EC2::NetworkInterface"
    Properties: 
      Description: Firebox Public Network Interface
      GroupSet:
        - !ImportValue FireboxSecurityGroup
      SubnetId: 
        !ImportValue FireboxPublicSubnet
      SourceDestCheck: false
  FireboxPrivateNetworkInterface:
    Type: "AWS::EC2::NetworkInterface"
    Properties: 
      Description: Firebox Private Network Interface
      GroupSet: 
        - !ImportValue FireboxSecurityGroup
      SubnetId: 
        !ImportValue FireboxPrivateSubnet
  Firebox: 
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: 
        Ref: ParamFireboxAMI
      InstanceType:
        Ref: ParamInstanceType
      NetworkInterfaces:
        - NetworkInterfaceId:
            Ref: FireboxPrivateNetworkInterface
          DeviceIndex: '0'
        - NetworkInterfaceId:
            Ref: FireboxPublicNetworkInterface
          DeviceIndex: '1'
Outputs:
  FireboxPrivateNetworkInterface:
    Value: !Ref FireboxPrivateNetworkInterface
    Export:
      Name: "FireboxPrivateNetworkInterface"
  FireboxPublicNetworkInterface:
    Value: !Ref FireboxPublicNetworkInterface
    Export:
      Name: "FireboxPublicNetworkInterface"
  Firebox:
    Value: !Ref Firebox
    Export:
      Name: "Firebox"