AWSTemplateFormatVersion: "2010-09-09"
Description: "Firebox Cloud Template"
Parameters: 
  ParamFireboxAMI:
    Type: String
    Default: ami-ac1798cc
    AllowedValues:
      - ami-ac1798cc
  ParamInstanceType: 
    Type: String
    Default: c4.large
    AllowedValues: 
      - t2.micro
      - t2.small
      - c4.large
    Description: Choose an allowed instance type.
  ParamStackName: 
    Type: String
    Default: "firebox-trial"
    Description: "Name used in resource tags and names"
Resources:
  Firebox: 
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: 
        Ref: ParamFireboxAMI
      InstanceType:
        Ref: ParamInstanceType
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          Description: Firebox Private Network Interface
          DeviceIndex: "0"
          GroupSet: 
            - !ImportValue FireboxSecurityGroup
          SubnetId: 
            !ImportValue FireboxPrivateSubnet
          DeleteOnTermination: true
  FireboxPublicNetworkInterface:
    Type: "AWS::EC2::NetworkInterface"
    Properties: 
      Description: Firebox Public Network Interface
      GroupSet:
        - !ImportValue FireboxSecurityGroup
      SubnetId: 
        !ImportValue FireboxPublicSubnet
      SourceDestCheck: false
  FireboxPublicENIAttachment:
    Type: "AWS::EC2::NetworkInterfaceAttachment"
    Properties: 
      DeleteOnTermination: true
      DeviceIndex: "1"
      InstanceId: 
        Ref: Firebox
      NetworkInterfaceId: 
        Ref: FireboxPublicNetworkInterface 
  FireboxElasticIP:
    Type: AWS::EC2::EIP
  FireboxEIPAssociation:
    Type: "AWS::EC2::EIPAssociation"
    Properties:
      InstanceId:
        Ref: Firebox
      EIP: 
        Ref: FireboxElasticIP
      NetworkInterfaceId:
        Ref: FireboxPublicNetworkInterface