AWSTemplateFormatVersion: "2010-09-09"
Description: "Firebox NAT Route"
Parameters: 
  ParamStackName: 
    Type: String
    Default: "firebox-trial"
    Description: "Name used in resource tags and names"
  ParamAllowedOutCidr: 
    Type: String
    Default: "0.0.0.0/0"
    Description: "CIDR block for allowed outbound traffic"
Resources:
  FireboxNATRoute:
    Type: "AWS::EC2::Route"
    Properties: 
      DestinationCidrBlock: 
        Ref: ParamAllowedOutCidr
      NetworkInterfaceId: 
        !ImportValue FireboxManagementNetworkInterface
      RouteTableId: 
       !ImportValue FireboxManagementRouteTable

