AWSTemplateFormatVersion: "2010-09-09"
Description: "Firebox private config bucket S3 endpoint"
#http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-endpoints.html
Parameters: 
  ParamStackName: 
    Type: String
    Default: "firebox-trial"
    Description: "Name used in resource tags and names"
Resources:
  FireboxCLIS3Endpoint:
    #http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html
    Type: "AWS::EC2::VPCEndpoint"
    Properties: 
      PolicyDocument: 
        Statement: 
          - 
            Sid: "Allow-GetObject-from-Firebox-Private-Bucket"
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !ImportValue FireboxPrivateBucketResourcesArn
      RouteTableIds:
        - !ImportValue FireboxCLIRouteTable
      ServiceName: !Join ['', [com.amazonaws., !Ref 'AWS::Region', .s3]]
      VpcId: !ImportValue FireboxVPC
Outputs:
  FireboxCLIS3Endpoint:
    Value: !Ref FireboxCLIS3Endpoint
    Export:
      Name: FireboxCLIS3Endpoint