AWSTemplateFormatVersion: "2010-09-09"
Description: "Firebox private config bucket S3 endpoint egresss rule"
Parameters: 
  ParamStackName: 
    Type: String
    Description: "Name used in resource tags and names"
  ParamPrefixListId:
    Type: String
    Description: "PrefixList ID for S3 endpoint"
Resources:
  #Egress rule for S3 endpoint in CLI Security Group
  #http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-security-group-egress.html
  FireboxCLISGEgressS3Endpoint:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !ImportValue FireboxManagementSecurityGroup
      DestinationPrefixListId: !Ref ParamPrefixListId
      IpProtocol: tcp
      ToPort: 443
      FromPort: 443