AWSTemplateFormatVersion: "2010-09-09"
Description: "Firebox CLI bucket S3 endpoint - NOT DONE"
Parameters: 
  ParamStackName: 
    Type: String
    Default: "firebox-trial"
    Description: "Name used in resource tags and names"
Resources:
  FireboxCLIS3Endpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties: 
      PolicyDocument: 
        Statement: 
          Action:
            - "s3:GetObject"
          Effect: "Allow"
          Resource: 
            Fn::Join: 
              - ""
              - 
                - "arn:aws:s3:::"
                - !ImportValue FireboxPrivateBucket
                - "/*"
          Principal: 
            AWS:
              !ImportValue FireboxLambdaCLIRoleArn
          Condition:
            StringNotEquals": 
              aws:sourceVpce
                !ImportValue FireboxVPC
      RouteTableIds:
        - !ImportValue FireboxCLIRouteTable
      ServiceName: !Join ['', [com.amazonaws., !Ref 'AWS::Region', .s3]]
      VpcId: !ImportValue FireboxVPC
Outputs:
  FireboxCLIS3Endpoint:
    Value: !Ref FireboxCLIS3Endpoint
    Export:
      Name: "FireboxCLIS3Endpoint"
